apiVersion: apps/v1
kind: Deployment
metadata:
  name: xray-okteto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xray-okteto
  template:
    metadata:
      labels:
        app: xray-okteto
    spec:
      containers:
      - image: funnymdzz/xray-okteto:latest
        name: xray-okteto
        ports:
        - containerPort: 443
